### PR TITLE
Fix scoped route references.

### LINKED ISSUE #517: scoped route consistency checking is wrong
I'm not convinced that I completely understand how scoped routes are put together, but I'm fairly sure that the consistency check is not correct. In `getListenerReferences`, we crack the connection manager and, if SRDS is being used, add the name of the scoped routes element to the set of resource references that we expect:

https://github.com/envoyproxy/go-control-plane/blob/d02f089307688a1fe99f1cdf9f66623f07707fa2/pkg/cache/v3/resource.go#L229-L234

However, this isn't how scoped routes work, because there should be a `ScopedRouteConfiguration` resource for every unique key. The name in the HCM `ScopedRoutes` fields is irrelevant and does not need to match any resources. IIUC, what happens is that Envoy collects all the `ScopedRouteConfiguration` resources, and indexes the correct one based on the results of the key builder match. There's no direct link between the HCM and the scoped route resources (seems like a problem with the API design).

So for consistency checking, I think that:
* `ScopedRouteConfiguration` resources should be checked to ensure they name a valid `RouteConfiguration`
* the name in the HCM `ScopedRoutes` field should not be checked
* if HCM enables SRDS, then at least one `ScopedRouteConfiguration` must be present
* additional `ScopedRouteConfiguration` resources are allowed

### PR DESCRIPTION
**Pull request by jpeach**
When setting the `ScopedRoutes` field in a `HttpConnectionManager`
resouce, the name provided in the `ScopedRoutes` field is not the
name of a `ScopedRouteConfiguration` xDS resource, it's just a name.
When scoped routing is being used, the control plane may provide any
number of `ScopedRouteConfiguration` resouces, which are not linked to
any specific `HttpConnectionManager`.

This fixes #517.

Signed-off-by: James Peach <jpeach@apache.org>

### CODE REVIEW

**Comment by jpeach** [comment]
@mtagstyle Are you able to review this?

**Comment by mtagstyle** [comment]
Thanks for the clarification in the other thread. I'll take a look at this tonight.

**Comment by alecholmez** [comment]
This looks great, I'll wait for @mtagstyle's review but you have an approval from my end

File: pkg/cache/v3/resource.go [hunk 1]
```diff
@@ -212,42 +210,18 @@ func getListenerReferences(src *listener.Listener, out map[resource.Type]map[str
...
+				routes[name] = true
 			}
-		}
-	}
 
-	if len(scopedRoutes) > 0 {
-		if _, ok := out[resource.ScopedRouteType]; !ok {
-			out[resource.ScopedRouteType] = map[string]bool{}
+			// If the scoped route mapping is embedded, add the referenced route resource names.
+			for _, s := range config.GetScopedRoutes().GetScopedRouteConfigurationsList().GetScopedRouteConfigurations() {
```
Comment (mtagstyle) [inline pkg/cache/v3/resource.go:219]: Should we be nil checking each call? 

Is there potential for GetScopedRoutes() to return nil? 
Is there potential for GetScopedRouteConfigurationsList() to return nil?

File: pkg/cache/v3/resource_test.go [hunk 2]
```diff
@@ -18,6 +18,8 @@ import (
 	"reflect"
 	"testing"
 
+	"github.com/stretchr/testify/assert"
```
Comment (mtagstyle) [inline pkg/cache/v3/resource_test.go:21]: Thanks for bringing this in. It will greatly simplify all the assertions

File: pkg/cache/v3/resource_test.go [hunk 3]
```diff
@@ -129,8 +121,8 @@ func TestGetResourceReferences(t *testing.T) {
 			out: map[rsrc.Type]map[string]bool{rsrc.EndpointType: {"test": true}},
 		},
 		{
-			in:  resource.MakeScopedRouteHTTPListener(resource.Xds, listenerName, 80, scopedRouteName),
-			out: map[rsrc.Type]map[string]bool{rsrc.ScopedRouteType: {scopedRouteName: true}},
+			in:  resource.MakeScopedRouteHTTPListener(resource.Xds, listenerName, 80),
```
Comment (mtagstyle) [inline pkg/cache/v3/resource_test.go:124]: Should we add a test case to check the embedded routes case? (I.e. MakeScopedRouteHTTPListenerForRoutes)

File: pkg/cache/v3/snapshot_test.go [hunk 4]
```diff
@@ -98,7 +98,7 @@ func TestScopedRouteListenerWithScopedRouteOnlyIsInconsistent(t *testing.T) {
 func TestScopedRouteListenerWithScopedRouteAndRouteIsConsistent(t *testing.T) {
 	snap, _ := cache.NewSnapshot(version, map[rsrc.Type][]types.Resource{
 		rsrc.ListenerType: {
-			resource.MakeScopedRouteHTTPListener(resource.Xds, "listener0", 80, "scopedRoute0"),
+			resource.MakeScopedRouteHTTPListener(resource.Xds, "listener0", 80),
```
Comment (mtagstyle) [inline pkg/cache/v3/snapshot_test.go:101]: I guess now, is it possible to have Scoped Routes. But have no HTTP Listeners in the filter chain using SRDS?

**Review by mtagstyle — CHANGES_REQUESTED** [review]
Thanks for getting to this before I did. Added some comments.

File: pkg/cache/v3/resource.go (hunk 1 above)
Comment (jpeach) [reply pkg/cache/v3/resource.go:219]: protobuf generates the `Get` accessors to gracefully handle nil objects. That's convenient for this kind of code because if any of the fields in the chain of references is nil, we will just end up ranging over a nil slice (which is a no-op).

File: pkg/cache/v3/snapshot_test.go (hunk 4 above)
Comment (jpeach) [reply pkg/cache/v3/snapshot_test.go:101]: Yeh, the reverse is also possible. I thought about implementing that, but balked at having to iterate and unpack the filters a second time and make a special case check for scoped routes. WDYT @alecholmez, is it worth it?

File: pkg/cache/v3/resource_test.go (hunk 3 above)
Comment (jpeach) [reply pkg/cache/v3/resource_test.go:124]: Yeh we might as well. Added this.

**Review by mtagstyle — APPROVED** [review]
LGTM. Just wanted that missing test case in.

File: pkg/cache/v3/snapshot_test.go (hunk 4 above)
Comment (alecholmez) [reply pkg/cache/v3/snapshot_test.go:101]: This is probably good for now, let's definitely note and potentially make an issue if that's something worth implementing down the road

**Review by alecholmez — APPROVED** [review]
